In [1]:
import pandas as pd

In [1]:
# 내장함수
# 파이썬 자체 내장함수()
var=[1,2,3,4]

sum(var)

10

In [2]:
max(var)

4

In [7]:
# 패키지함수
# 패키지명.적용함수()
import pandas as pd
ds=pd.read_csv('../../datasets/public/exam.csv')
df=pd.DataFrame({'x' : [1,2,3]})

In [8]:
ds

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [9]:
df

   x
0  1
1  2
2  3

In [10]:
# 메서드
# 변수가 지닌 함수
ds.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [12]:
# head는 데이터프레임에만 들어있는 메서드이기 때문에 리스트에는 사용불가
var.head()

AttributeError: 'list' object has no attribute 'head'

In [14]:
# 변수의 자료구조는 type()으로 알 수 있음
print('ds : ',type(ds))
print('df : ',type(df))
print('var : ',type(var))

ds :  <class 'pandas.core.frame.DataFrame'>
df :  <class 'pandas.core.frame.DataFrame'>
var :  <class 'list'>

In [15]:
# 어트리뷰트
# 괄호가 뒤에 붙으면 메서드, 없으면 어트리뷰트

# 마찬가지로 데이터프레임에만 사용되는 어트리뷰트는 리스트에 사용할 수 없음
print('df : ',df.shape)
print('var : ',var.shape)

df :  (3, 1)

AttributeError: 'list' object has no attribute 'shape'

In [18]:
df_raw=pd.DataFrame({'var1':[2,3,1],
                    'var2':[5,4,2]})
df_raw

   var1  var2
0     2     5
1     3     4
2     1     2

In [19]:
# 데이터 변형 시 복사본을 만드는게 좋음
df_new=df_raw.copy()
df_new

   var1  var2
0     2     5
1     3     4
2     1     2

In [20]:
# 변수명 바꾸기
df_new=df_new.rename(columns={'var2' : 'v2'})
df_new

   var1  v2
0     2   5
1     3   4
2     1   2

In [21]:
# 파생변수 : 기존 변수를 변형해서 새로 만든 변수

df_var=pd.DataFrame({'var1':[2,5,3,6],
                    'var2':[5,6,1,2]})
df_var

   var1  var2
0     2     5
1     5     6
2     3     1
3     6     2

In [22]:
df_var['var_sum']=df_var['var1']+df_var['var2']
df_var

   var1  var2  var_sum
0     2     5        7
1     5     6       11
2     3     1        4
3     6     2        8

In [25]:
df_var['var_mean']=df_var['var_sum']/2
df_var

   var1  var2  var_sum  var_mean
0     2     5        7       3.5
1     5     6       11       5.5
2     3     1        4       2.0
3     6     2        8       4.0