In [1]:
import pandas as pd

In [ ]:
# 데이터를 직접 입력해 데이터 프레임을 만들어보자
# 데이터 프레임을 만들 때는 pandas의 DataFrame()을 이용한다.

In [4]:
df=pd.DataFrame({'name' : ['KimGijun', 'LeeJin', 'ParkDong', 'KimMingi'],
                 'english' : [90,80,60,70],
                 'math' : [50,60,100,20]})
df
# 인덱스는 0부터 시작한다.
# 함수 안에 중괄호 안에 딕셔너리 (key,  value(리스트도 가능))로 사용가능

       name  english  math
0  KimGijun       90    50
1    LeeJin       80    60
2  ParkDong       60   100
3  KimMingi       70    20

In [8]:
sum(df['english'])
# 시험 성적 중 영어 성적의 합

300

In [9]:
sum(df['math'])/4
# 시험 성적 중 수학 성적의 평균

57.5

In [11]:
# 혼자서 해보기
df_fruit=pd.DataFrame({'제품': ['사과', '딸기', '수박'],
                      '가격' : [1800, 1500, 3000],
                      '판매량' : [24, 38, 13]})
df_fruit

   제품    가격  판매량
0  사과  1800   24
1  딸기  1500   38
2  수박  3000   13

In [16]:
sales_avg=sum(df_fruit['판매량'])/3
sales_avg

25.0

In [15]:
price_avg=sum(df_fruit['가격'])/3
price_avg

2100.0